package com.example.musicplayer.model;

import android.os.Parcel;
import android.util.Log;

import java.util.ArrayList;
import java.util.UUID;

public class PlaylistModel {
    private String playlistId;
    private String playlistName = "Unknown";
    private String playlistImagePath;
    private ArrayList<SongModel> listSong = new ArrayList<>();;

    public PlaylistModel( String playlistName) {
        UUID uuid = UUID.randomUUID();
        String uuidString = uuid.toString().replace("-", "");
        String autoGeneratedId = uuidString.substring(0, 10);
        this.playlistId = autoGeneratedId;
        this.playlistName = playlistName;
    }
    public PlaylistModel(String playlistId, String playlistName){
        this.playlistId = playlistId;
        this.playlistName = playlistName;
    }
    public PlaylistModel(String playlistId, String playlistName, ArrayList<SongModel> listSong){
        this.playlistId = playlistId;
        this.playlistName = playlistName;
        Log.d("List songs", String.valueOf(listSong));
        this.listSong = listSong;
    }

    public String getPlaylistId() {
        return playlistId;
    }


    public String getPlaylistName() {
        return playlistName;
    }


    public String getPlaylistImagePath() {
        if(this.listSong.size()>0) {
            return listSong.get(0).getPath();
        } else {
            return playlistImagePath;
        }
    }

    public ArrayList<SongModel> getListSong() {
        return listSong;
    }
}
